name: Build CV

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set executable permissions
        run: chmod +x bin/*sh

      - name: Build LaTeX document
        uses: docker://adnrv/texlive:full
        with:
          args: "/github/workspace/bin/build.sh"

      - name: Commit back
        run: |
          echo "${{ secrets.SFTP_KEY }}"  >/tmp/sftp_rsa
          chmod 0600 /tmp/sftp_rsa
          git commit -m '[skip CI] Updated files by bot' -a
          git push 
          bin/sync-up.sh

  