name: Build CV

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x bin/*sh

      - name: Build LaTeX document
        uses: docker://adnrv/texlive:full
        with:
          args: "/github/workspace/bin/build.sh"

      # - name: Commit back
      #   uses: peaceiris/actions-gh-pages@v3.9.3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: .
      #     publish_branch: draft
      #     keep_files: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[skip-ci] New CV prepared"
          title: A new CV has been prepared
          body: |
            Successful compilation of CV

          branch: draft  # Replace with your branch name
          branch-suffix: timestamp  # Optional: Add a timestamp to the branch name

      - name: Push CV
        run: |
          echo "${{ secrets.SFTP_KEY }}"  >/tmp/sftp_rsa
          chmod 0600 /tmp/sftp_rsa
          bin/sync-up.sh

  