name: Build CV

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set executable permissions
        run: chmod +x bin/*sh

      - name: Build LaTeX document
        uses: docker://adnrv/texlive:full
        with:
          args: "/github/workspace/bin/build.sh"

      - name: Commit back
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: master

      - name: Push CV
        run: |
          echo "${{ secrets.SFTP_KEY }}"  >/tmp/sftp_rsa
          chmod 0600 /tmp/sftp_rsa
          bin/sync-up.sh

  